# Generated by Django 6.0.3 on 2026-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ETB', 'Ethiopian Birr'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('KES', 'Kenyan Shilling'), ('ZAR', 'South African Rand')], max_length=30)),
            ],
        ),
    ]
