# Generated by Django 6.0.3 on 2026-03-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='discription',
            new_name='description',
        ),
    ]
