# Generated by Django 6.0.3 on 2026-03-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cafe_chair_table_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='order.cafe'),
            preserve_default=False,
        ),
    ]
