# Generated by Django 6.0.3 on 2026-03-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_menu_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cafe',
        ),
        migrations.AddField(
            model_name='menu',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='order.table'),
            preserve_default=False,
        ),
    ]
