# Generated by Django 6.0.3 on 2026-03-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_menu_cafe_menu_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='table',
            name='chair',
        ),
        migrations.AddField(
            model_name='chair',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='order.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='order.cafe'),
            preserve_default=False,
        ),
    ]
