# Generated by Django 6.0.3 on 2026-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_menu_table_menu_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='chair_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.PositiveIntegerField(),
        ),
    ]
