# Generated by Django 6.0.3 on 2026-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_table_order_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chair',
            name='occupied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
