# Generated by Django 6.0.3 on 2026-04-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_cart_remove_order_item_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='order_time',
        ),
    ]
